import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Button } from "@/components/ui/button"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <h1>OHIF Component Design</h1> 
          <h2>Button</h2>
          <div className="row">
            <div className="example"><Button variant="default">Primary Button</Button></div>
            <div className="example"><Button variant="secondary">Secondary Button</Button></div>
            <div className="example"><Button variant="ghost">Ghost Button</Button></div>
            <div className="example"><Button variant="outline">Button</Button></div>
            <div className="example"><Button variant="link">Link</Button></div>
          </div>
          <h2>Button</h2>

        <p><Button variant="ghost" size="icon">?</Button></p>
        <p>.</p>
        <p>
        <Select>
          <SelectTrigger className="w-[180px]">
            <SelectValue placeholder="Theme" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="light">Light</SelectItem>
            <SelectItem value="dark">Dark</SelectItem>
            <SelectItem value="system">System</SelectItem>
          </SelectContent>
        </Select>
        </p>
        </main>
        {children}
      </body>
    </html>
  );
}
